name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npx eslint
